#status bar

# *******************************************************
#                   Customs
# *******************************************************

set-option -g status-position top
set -g set-clipboard on

# *******************************************************
# set-option -g status-utf8 on
# set-option -g default-shell /bin/zsh
set -g status-interval 1
set -g status-justify centre # center align window list
set -g status-left-length 20
set -g status-right-length 140
#set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r | cut -c 1-6)#[default]'
#set -g status-right '#[fg=green]#(tmux-mem-cpu-load 1) #[]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") %a%l:%M:%S %p %Y-%m-%d'

# default statusbar colors
#set -g status-fg white
#set -g status-bg default

#set -g window-active-style 'fg=colour214'

# default window title colors

# active window title colors
#set-window-option -g window-status-current-fg white
#set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright
# C-b is not acceptable -- Vim uses it
set-option -g prefix C-Space
bind-key C-Space last-window

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Highlight active window
# set-window-option -g window-status-current-bg white

# Vi copypaste mode
# set-window-option -g mode-keys vi
# bind-key -t vi-copy 'v' begin-selection
# bind-key -t vi-copy 'y' copy-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"
bind-key p run "xsel -o | tmux load-buffer - ; tmux paste-buffer"

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# auto window rename
# set-window-option -g automatic-rename

# rm mouse mode fail
set -g mouse on

# color
set -g default-terminal "xterm-256color"

# Sane scrolling
# TODO: make sure this works in OSX
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

set -g pane-active-border-style fg=colour12,bg=default

#PLUGINS

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @plugin 'jimeh/tmux-themepack'
# set -g @themepack 'powerline/block/blue'

# tmux power theme
set -g @plugin 'wfxr/tmux-power'
# set -g @tmux_power_date_icon ' ' # set it to a blank will disable the icon
# set -g @tmux_power_time_icon ' ' # emoji can be used if your terminal supports
# set -g @tmux_power_user_icon ' '
# set -g @tmux_power_session_icon ' '
# set -g @tmux_power_upload_speed_icon '↑'
# set -g @tmux_power_download_speed_icon '↓'
# set -g @tmux_power_left_arrow_icon ' '
# set -g @tmux_power_right_arrow_icon ' '
set -g @tmux_power_theme 'white'
# set -g @tmux_power_theme '#d7a161'
# set -g @tmux_power_theme '#5f8787'
# set -g @plugin 'dracula/tmux'  
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
